promisify
PrismarineJS/mineflayer-tool pull request #17
Opened 2021-03-11 19:14 UTC by u9g

2021-05-23 08:59 UTC, TheDudeFromCI requested changes

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Inventory.ts
> +export const standardToolFilter = ({ name }: Item): boolean => name.test(/sword|pickaxe|shovel|axe|hoe/)
Format is `regex,test(string)`

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Inventory.ts
>    const pathfinder = bot.pathfinder
`// @ts-expect-error` is required for ts to compile.

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Inventory.ts
> +  bot.once('goal_reached', cb)
`bot.once` cannot be used here as `goal_update` is not guaranteed to be called.

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Inventory.ts
> +  bot.once('path_update', (results: ComputedPath) => {
`bot.once` cannot be used here as `path_update` is not guaranteed to be called only once. (May be called many times before being removed.)

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Inventory.ts
> +  bot.once('goal_updated', () => {
`bot.once` cannot be used here as `goal_update` is not guaranteed to be called.

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Tool.ts
>      const effects = this.bot.entity.effects
`// @ts-expect-error` is required here for ts to compile.

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/Tool.ts
>      return block.digTime(item?.type, false, false, false, enchants, effects)
`// @ts-expect-error` is required here for ts to compile.

2021-05-23 08:59 UTC, TheDudeFromCI commented on src/index.ts
>      if (bot.pathfinder == null) {
`// @ts-expect-error` is required here for ts to compile.

2021-06-16 21:09 UTC, rom1504 commented
will this be finished ?

2021-09-24 01:06 UTC, closed without merging